DOG_BREEDS = [
    'Affenpinscher',
    'Afghan hound',
    'African hunting dog',
    'Airedale',
    'American staffordshire terrier',
    'Appenzeller',
    'Australian terrier',
    'Basenji',
    'Basset',
    'Beagle',
    'Bedlington terrier',
    'Bernese mountain dog',
    'Black and tan coonhound',
    'Blenheim spaniel',
    'Bloodhound',
    'Bluetick',
    'Border collie',
    'Border terrier',
    'Borzoi',
    'Boston bull',
    'Bouvier des flandres',
    'Boxer',
    'Brabancon griffon',
    'Briard',
    'Brittany spaniel',
    'Bull mastiff',
    'Cairn',
    'Cardigan',
    'Chesapeake bay retriever',
    'Chihuahua',
    'Chow',
    'Clumber',
    'Cocker spaniel',
    'Collie',
    'Curly coated retriever',
    'Dandie dinmont',
    'Dhole',
    'Dingo',
    'Doberman',
    'English foxhound',
    'English setter',
    'English springer',
    'Entlebucher',
    'Eskimo dog',
    'Flat coated retriever',
    'French bulldog',
    'German shepherd',
    'German short haired pointer',
    'Giant schnauzer',
    'Golden retriever',
    'Gordon setter',
    'Great dane',
    'Great pyrenees',
    'Greater swiss mountain dog',
    'Groenendael',
    'Ibizan hound',
    'Irish setter',
    'Irish terrier',
    'Irish water spaniel',
    'Irish wolfhound',
    'Italian greyhound',
    'Japanese spaniel',
    'Keeshond',
    'Kelpie',
    'Kerry blue terrier',
    'Komondor',
    'Kuvasz',
    'Labrador retriever',
    'Lakeland terrier',
    'Leonberg',
    'Lhasa',
    'Malamute',
    'Malinois',
    'Maltese dog',
    'Mexican hairless',
    'Miniature pinscher',
    'Miniature poodle',
    'Miniature schnauzer',
    'Newfoundland',
    'Norfolk terrier',
    'Norwegian elkhound',
    'Norwich terrier',
    'Old english sheepdog',
    'Otterhound',
    'Papillon',
    'Pekinese',
    'Pembroke',
    'Pomeranian',
    'Pug',
    'Redbone',
    'Rhodesian ridgeback',
    'Rottweiler',
    'Saint bernard',
    'Saluki',
    'Samoyed',
    'Schipperke',
    'Scotch terrier',
    'Scottish deerhound',
    'Sealyham terrier',
    'Shetland sheepdog',
    'Shih tzu',
    'Siberian husky',
    'Silky terrier',
    'Soft coated wheaten terrier',
    'Staffordshire bullterrier',
    'Standard poodle',
    'Standard schnauzer',
    'Sussex spaniel',
    'Tibetan mastiff',
    'Tibetan terrier',
    'Toy poodle',
    'Toy terrier',
    'Vizsla',
    'Walker hound',
    'Weimaraner',
    'Welsh springer spaniel',
    'West highland white terrier',
    'Whippet',
    'Wire haired fox terrier',
    'Yorkshire terrier'
]
